### ISSUE TITLE
[Bug]Queue Gets stuck + Inconsistent Flashcard Number

### ISSUE THREAD

**Issue by webtaphip** [bjsi/incremental-everything#42] opened 2023-09-17 06:33 UTC
https://github.com/bjsi/incremental-everything/assets/143251037/0c513ef7-1540-4086-a147-4e8765d20fc8

**Comment by bjsi** [comment] 2023-09-20 10:21
Hmm I'm not sure why this is happening. It could be caused by incremental Rem with clozes. I will investigate :+1:

**Comment by webtaphip** [comment] 2023-09-22 06:33
I have noticed that i never get tested for cloze "Metablosim" ,"Preservation" .

**Comment by bjsi** [comment] 2023-10-02 10:32
Should be fixed in the latest version

**Closed by bjsi** 2023-10-02 10:32 UTC
