### ISSUE TITLE
[FEATURE] Need a button to remind what is being incremented.

### ISSUE THREAD

**Issue by ObeyYourHeart** [bjsi/incremental-everything#9] opened 2023-08-25 19:24 UTC
This is to solve the problem of web reader - when there are multiple highlights being incremented on the same page, it is impossible to know which one is currently being incremented. This button is similar to the pin function in reader, and clicking it will render the current increment of rem. I think this method is simple.

**Comment by bjsi** [comment] 2023-08-26 06:30
Closing as duplicate of https://github.com/bjsi/incremental-everything/issues/14

**Closed by bjsi** 2023-08-26 06:30 UTC
